version: "3.0"
services:

  mssql:
    build:
      context: ./src/db/build
      args:
      - sapw=GAOchuang900529
    ports:
      - "1433:1433"
    volumes:
      - "leaf-mssql:/var/opt/mssql"
      - "/src/db/bak:/bak"
    networks:
      local:
        aliases:
          - mssql
  
  node:
    build: ./src/ui-client
    restart: on-failure
    ports:
      - 3000:3000
    #command: ["npm", "start"]
    depends_on:
      - mssql
  #   - coreapi

  # coreapi:
  #   build: 
  #     context: ./src/server
  #     dockerfile: ./src/server/Dockerfile.dev
  #   ports:
  #     - "5001:5001"
  #   depends_on:
  #     - mssql
  #   volumes:
  #     - ./src/server:/app
  #     - ${KEYS}:/.keys
  #     - ${LOGGING_DIR}:/logs
  #   environment:
  #     LEAF_JWT_CERT: ${JWT_CERT}
  #     LEAF_JWT_KEY: ${JWT_KEY}
  #     LEAF_JWT_KEY_PW: ${JWT_KEY_PW}
  #     LEAF_APP_DB: ${APP_DB}
  #     LEAF_CLIN_DB: ${CLIN_DB}
  #     SERILOG_DIR: /logs
  #   working_dir: "/app/API"
  #   command: ["dotnet", "run"]
  #   networks:
  #     local:
  #       aliases:
  #         - coreapi

volumes:
  leaf-mssql:

networks:
  local:
    driver: bridge

